apiVersion: v1
kind: Namespace
metadata:
  name: cn-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cn-crd-discovery
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cn-crd-discovery
subjects:
  - kind: ServiceAccount
    name: cn-crd-discovery
    namespace: cn-system
roleRef:
  kind: ClusterRole
  name: cn-crd-discovery
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cn-crd-discovery
  namespace: cn-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd-discovery-server
  namespace: cn-system
  labels:
    app: crd-discovery-server
    src: cloudnativeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crd-discovery-server
      src: cloudnativeapp
  template:
    metadata:
      labels:
        app: crd-discovery-server
        src: cloudnativeapp
    spec:
      serviceAccountName: cn-crd-discovery
      containers:
        - name: crd-discovery-server
          image: somefive/crd-discovery:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
